language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: T2jkUn8uY73hSTBg95X8t3smC4IqvuqCjI5q0Pkl8/MLM13zgONeoojFMlgQO04trnmoKBoBZf1VIJkxXSOROYvChh9BTwgPJsckaU4vDb4oan23ZRUMn2nEM0wK0+8MmajsF+z2U1oX3KCD9lsWIgQwqhSEUzUpfCYOPD9OjoG7Fea0l6QH5jrD8P99I8fziQl24y9kJXsL2qcvJrBhD/pHSTwlreMmI6PC39LGhNGRDKWlxTEabr1ZtIr592JgIQmCoiBNjuM6/OnUEVEHBLMgSrZUYVZst6iWwfr9AgENpO99pcVv/NrMjs50VGRLoB7aqSojOCs7livOTLs2l4oX8slh3RRdPrFOgCiQxiS7RIiv1hK/1ySh4j+9uCIfVA0bS9b4K+mOOdL6vIMMGGk0q9zAXLcjKcq5l01nLZMq0m6lwMqc2QXfc18qfZT1jsW6onjLYEJMafklXHnddqAbMJZXm430HAM1VDO7Z/dq9ZQTj+oF9VT8WIocflrRRcZU9CYArlQkAuT5Z0QRCuwY8icyyx8fH7DBCY4oPrhkuYmJiaDcFckPMMBYIwem0FLsBuG8BeKXxPq5XyTzXjmEbfqEI+idA1Q78dfrcE49YIK6ul5qn9tIxWFLwkwuyiD2b1k5IbO5723AKyGdDw0SaeCHn3mKN07ivZ9fU7o=
  app: 
  run: rails db:migrate
